### Install Pandas if not already installed

In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\softwares\python3_12\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\softwares\python3_12\lib\site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\softwares\python3_12\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\softwares\python3_12\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\softwares\python3_12\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\softwares\python3_12\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

### Import pandas

In [2]:
import pandas as pd

### Read Different Types of Files

#### .csv File

In [6]:
df_csv = pd.read_csv( 'transactions.csv' )
df_csv

,TransactionID,Date,Time,Item,Quantity,PricePerItem,TotalPrice,PaymentMethod
0,TX1001,2025-09-08,08:15:23,Cappuccino,1.0,3.50,3.50,Credit Card
1,TX1002,2025-09-01,08:22:11,Latte,2.0,4.00,8.00,Cash
2,TX1003,2025-09-12,08:35:46,Espresso,1.0,2.75,2.75,Mobile Pay
3,TX1004,2025-09-03,08:50:39,Croissant,1.0,2.50,2.50,Credit Card
4,TX1005,2025-09-07,09:00:02,Americano,1.0,3.00,3.00,NaN
5,TX1006,2025-09-02,09:05:55,Mocha,NaN,4.25,NaN,Mobile Pay
6,TX1007,2025-09-15,09:15:08,Tea,1.0,NaN,2.25,Credit Card
7,TX1008,2025-09-05,09:30:42,Latte,1.0,4.00,4.00,Mobile Pay
8,TX1009,2025-09-04,09:45:14,Bagel,1.0,2.75,2.75,Cash
9,TX1010,2025-09-10,10:00:27,Cappuccino,2.0,3.50,7.00,Credit Card

#### .xlsx File

In [7]:
df_xls = pd.read_excel( 'quotes_scraped.xlsx' )
df_xls

,Quote Text,Author,Tags
0,â€œThe world as we have created it is a proces...,Albert Einstein,"change, deep-thoughts, thinking, world"
1,"â€œIt is our choices, Harry, that show what we...",J.K. Rowling,"abilities, choices"
2,â€œThere are only two ways to live your life. ...,Albert Einstein,"inspirational, life, live, miracle, miracles"
3,"â€œThe person, be it gentleman or lady, who ha...",Jane Austen,"aliteracy, books, classic, humor"
4,"â€œImperfection is beauty, madness is genius a...",Marilyn Monroe,"be-yourself, inspirational"
5,â€œTry not to become a man of success. Rather ...,Albert Einstein,"adulthood, success, value"
6,â€œIt is better to be hated for what you are t...,AndrÃ© Gide,"life, love"
7,"â€œI have not failed. I've just found 10,000 w...",Thomas A. Edison,"edison, failure, inspirational, paraphrased"
8,â€œA woman is like a tea bag; you never know h...,Eleanor Roosevelt,misattributed-eleanor-roosevelt
9,"â€œA day without sunshine is like, you know, n...",Steve Martin,"humor, obvious, simile"

#### .json File

In [8]:
df_json = pd.read_json( 'users.json' )
df_json

,firstName,lastName,age,driversLicenceNumber,isProgrammer,isTester,emailAddress,phoneNumber,country,city,address
0,John,Doe,25,None,True,False,JohnDoe@gmail.com,(987) 654-3210,USA,New York,123 Main St.
1,Jane,Doe,30,987-654-321,False,True,JaneDoe@outlook.com,(123) 456-7890,Canada,Toronto,987 Yonge St.

***