#### Import Required Libraries

In [1]:
import pandas as pd
import sqlite3

In [2]:
conn = sqlite3.connect("EmpDB/EmpDB.db")

df = pd.read_sql_query( 'SELECT * FROM Employee', conn )
df

   empId          empName   empDept  empSalary   empCity empCountry
0      1   Harvey Specter     Legal   100000.0  New York        USA
1      2  Jessica Pearson       CEO   200000.0   Seattle        USA
2      3        Mike Ross  Research    75000.0   Toronto     Canada
3      4       Louis Litt       COO   150000.0    London         UK

#### Information About the DataFrame

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   empId       4 non-null      int64
 1   empName     4 non-null      object
 2   empDept     4 non-null      object
 3   empSalary   4 non-null      float64
 4   empCity     4 non-null      object
 5   empCountry  4 non-null      object
dtypes: float64(1), int64(1), object(4)
memory usage: 324.0+ bytes

#### Statistical Info about the DataFrame

In [4]:
df['empSalary'].describe()

count         4.000000
mean     131250.000000
std       55433.894565
min       75000.000000
25%       93750.000000
50%      125000.000000
75%      162500.000000
max      200000.000000
Name: empSalary, dtype: float64

#### Size and Shape

In [5]:
print( 'Total Number of Items:', df.size )
print( 'Number of Rows,Cols:', df.shape )

Total Number of Items: 24
Number of Rows,Cols: (4, 6)

#### Sort Employees based on Salary

In [6]:
# Ascending
df.sort_values('empSalary')
# Descending
# df.sort_values('empSalary', ascending=False)

   empId          empName   empDept  empSalary   empCity empCountry
2      3        Mike Ross  Research    75000.0   Toronto     Canada
0      1   Harvey Specter     Legal   100000.0  New York        USA
3      4       Louis Litt       COO   150000.0    London         UK
1      2  Jessica Pearson       CEO   200000.0   Seattle        USA

***

### Display Pandas DataFrame as a HTML Document

##### Normal Display without Styling

In [7]:
df.to_html( 'data1.html', index=False, border=1 )

##### CSS Styling Added

In [8]:
# CSS styling for the HTML table and webpage
css = """
<style>
  body { background: lightgoldenrodyellow; margin: 0; padding: 20px; font-family: Arial, sans-serif; }
  .s2 { width: 100%; border-collapse: separate; font-size: 14px; }
  .s2 th { background: #0C447C; color: #E6F1FB; padding: 9px 14px; text-align: left; }
  .s2 td { background: #E6F1FB; padding: 8px 14px; color: #042C53; }
</style>
"""

# index=False removes row numbers and apply CSS styling specified above
html = df.to_html( index=False, border=0, classes='s2' )

# Create and write the styled HTML output into a file
with open('data2.html', 'w') as f:
    f.write(css + html)

# Close the database connection
conn.close()

***